class ContactsPageLocators:
    PAGE_TITLE = "h1"
    MAIN_CONTENT = "main, .content, .contacts-content"
    PHONE = "a[href^='tel:'], .phone"
    EMAIL = "a[href^='mailto:'], .email"
    ADDRESS = ".address, address"
    CONTACT_FORM = "form, .contact-form, .feedback-form"
    NAME_INPUT = "input[name*='name'], input[placeholder*='Имя']"
    EMAIL_INPUT = "input[type='email'], input[name*='email']"
    PHONE_INPUT = "input[type='tel'], input[name*='phone']"
    MESSAGE_INPUT = "textarea, input[name*='message']"
    SUBMIT_BUTTON = "button[type='submit'], input[type='submit'], .submit-btn"
    MAP = ".map, #map, iframe[src*='map']"
    SOCIAL_LINKS = ".social a, .socials a"
