class MainPageLocators:
    HEADER = "header, .header, [class*='header'], nav, .nav"
    NAV_MENU = "nav, .nav, .menu, .navigation, [class*='nav']"
    LOGO = "a[href='/'] img, .logo, a.logo, [class*='logo'], img[alt*='logo']"
    ABOUT_LINK = "a[href*='about'], a[href*='o-nas'], a:has-text('О нас'), a:has-text('О компании'), a:has-text('About')"
    CONTACTS_LINK = "a[href*='contact'], a[href*='kontakt'], a:has-text('Контакты'), a:has-text('Contact')"
    SERVICES_LINK = "a[href*='service'], a[href*='uslug'], a:has-text('Услуги'), a:has-text('Service')"
    PORTFOLIO_LINK = "a[href*='portfolio'], a[href*='project'], a[href*='case'], a[href*='work'], a:has-text('Портфолио'), a:has-text('Проекты'), a:has-text('Кейсы'), a:has-text('Portfolio')"
    CAREER_LINK = "a[href*='career'], a[href*='vacanc'], a[href*='job'], a:has-text('Карьера'), a:has-text('Вакансии')"
    HERO_SECTION = ".hero, .banner, .main-banner, section:first-of-type, [class*='hero'], [class*='banner']"
    MAIN_TITLE = "h1"
    SERVICES_SECTION = "#services, .services, section:has-text('Услуги'), [class*='service']"
    PORTFOLIO_SECTION = "#portfolio, .portfolio, section:has-text('Портфолио'), [class*='portfolio']"
    ABOUT_SECTION = "#about, .about, section:has-text('О нас'), [class*='about']"
    CTA_BUTTON = ".btn, button, a.button, .cta, [class*='btn'], [class*='button']"
    CONTACT_BUTTON = "a[href*='contact'] .btn, button:has-text('Связаться'), a:has-text('Оставить заявку'), a:has-text('Заказать')"
    FOOTER = "footer, .footer, [class*='footer']"
    FOOTER_LINKS = "footer a, .footer a"
    PAGE_BODY = "body"
