class MainPageLocators:
    HEADER = "header"
    NAV_MENU = "nav, .nav, .menu, .navigation"
    LOGO = "a[href='/'] img, .logo, a.logo"
    ABOUT_LINK = "a[href*='about'], a:has-text('О нас'), a:has-text('О компании')"
    CONTACTS_LINK = "a[href*='contact'], a:has-text('Контакты')"
    SERVICES_LINK = "a[href*='service'], a:has-text('Услуги')"
    PORTFOLIO_LINK = "a[href*='portfolio'], a:has-text('Портфолио'), a:has-text('Проекты'), a:has-text('Кейсы')"
    CAREER_LINK = "a[href*='career'], a[href*='vacanc'], a:has-text('Карьера'), a:has-text('Вакансии')"
    HERO_SECTION = ".hero, .banner, .main-banner, section:first-of-type"
    MAIN_TITLE = "h1"
    SERVICES_SECTION = "#services, .services, section:has-text('Услуги')"
    PORTFOLIO_SECTION = "#portfolio, .portfolio, section:has-text('Портфолио')"
    ABOUT_SECTION = "#about, .about, section:has-text('О нас')"
    CTA_BUTTON = ".btn, button, a.button, .cta"
    CONTACT_BUTTON = "a[href*='contact'] .btn, button:has-text('Связаться'), a:has-text('Оставить заявку')"
    FOOTER = "footer"
    FOOTER_LINKS = "footer a"
