class PortfolioPageLocators:
    PAGE_TITLE = "h1"
    MAIN_CONTENT = "main, .content, .portfolio-content"
    PROJECTS_LIST = ".projects, .portfolio-list, .cases"
    PROJECT_ITEM = ".project, .portfolio-item, .case, .case-item"
    PROJECT_TITLE = ".project-title, .case-title, h3"
    PROJECT_IMAGE = ".project-image img, .case-image img"
    PROJECT_LINK = ".project a, .case a, .view-project"
    FILTER_ALL = ".filter-all, button:has-text('Все')"
    FILTER_MOBILE = ".filter-mobile, button:has-text('Мобильные')"
    FILTER_WEB = ".filter-web, button:has-text('Веб')"
    PAGINATION = ".pagination"
    NEXT_PAGE = ".pagination .next, a:has-text('Далее')"
    PREV_PAGE = ".pagination .prev, a:has-text('Назад')"
